### PR TITLE
Fix diagnostic writing for coupled N-deposition

### PR DESCRIPTION
**Pull request by jmaerz**
This PR fixes the writing of diagnostics for N-deposition.  It has been already fixed in `master` by PR #410.

### CODE REVIEW

**Review by TomasTorsvik — APPROVED** [review]
@jmaerz - approved!
Is this all that you what you want to "cherry-pick" from #410 into the `release-1.6` branch?

**Comment by jmaerz** [comment]
Hi @TomasTorsvik , yes, I think so - in NorESM2.3, MCT is still the default, if I am not mistaken?!

**Comment by TomasTorsvik** [comment]
> Hi @TomasTorsvik , yes, I think so - in NorESM2.3, MCT is still the default, if I am not mistaken?!

Yes, that is correct.

**Comment by jmaerz** [comment]
Then I am not seeing any reason to pick more than this change from #410. Or do you?

**Comment by TomasTorsvik** [comment]
> Then I am not seeing any reason to pick more than this change from #410. Or do you?

No, I think it's fine.

**Pull request merged**
