### PR TITLE
Fixed several instances of truncated F77 fix-source format code lines in iHAMOCC

### PR DESCRIPTION
**Pull request by JorgSchwinger**
This solves a problem that @nordmoen encountered in #66

### CODE REVIEW

**Comment by nordmoen** [comment]
There are a few other places this is happening as well, I'll try to list the ones I have encountered.

```bash
../hamocc/blom2hamocc.F:156:72:                                                  
                                                                                 
  156 |         ocetra(i,j,k,:)=trc(i,j,kn,itrbgc:itrbgc+ntrbgc-1)*bgc_rho(i,j,k)
      |                                                                        1 
Warning: Line truncated at (1) [-Wline-truncation]                               
```

```bash
../hamocc/trc_limitc.F:72:72:                                                         
                                                                                      
   72 |             util1(i,j)=util1(i,j)+trc(i,j,kn,itrbgc+nt-1)*dp(i,j,kn)*scp2(i,j)
      |                                                                        1      
Warning: Line truncated at (1) [-Wline-truncation]                                    
```

```bash
../hamocc/trc_limitc.F:112:72:                                                        
                                                                                      
  112 |             util1(i,j)=util1(i,j)+trc(i,j,kn,itrbgc+nt-1)*dp(i,j,kn)*scp2(i,j)
      |                                                                        1      
Warning: Line truncated at (1) [-Wline-truncation]                                    
```

```bash
../hamocc/hamocc2blom.F:72:72:                                                   
                                                                                 
   72 |         trc(i,j,kn,itrbgc:itrbgc+ntrbgc-1)=ocetra(i,j,k,:)/bgc_rho(i,j,k)
      |                                                                        1 
Warning: Line truncated at (1) [-Wline-truncation]                               
```

**Comment by JorgSchwinger** [comment]
I have now also fixed the other instances of truncated lines.

**Comment by nordmoen** [comment]
I pulled your changes and new lines are discovered.

```bash
../hamocc/hamocc_init.F:55:72:                                                   
                                                                                 
   55 |       use mo_Gdata_read, only: inidic,inialk,inipo4,inioxy,inino3,inisil,
      |                                                                        1 
Warning: Line truncated at (1) [-Wline-truncation]                               
```

```bash
../hamocc/hamocc_init.F:99:72:                                                               
                                                                                             
   99 |       open (unit=io_nml,file='ocn_in'//trim(inst_suffix),status='old',action='read') 
      |                                                                        1             
Warning: Line truncated at (1) [-Wline-truncation]                                           
```

**Comment by JorgSchwinger** [comment]
I have fixed hamocc_init.F, too. Can you give it another try @nordmoen?

**Comment by nordmoen** [comment]
That seemed to have fixed it! I added the changes to PR #66.

**Comment by JorgSchwinger** [comment]
Ok great! Thanks for pointing this out. It's good to have the code conforming to the standard, even if it is a very old standard and many compilers don't care...

**Comment by nordmoen** [comment]
> Ok great! Thanks for pointing this out. It's good to have the code conforming to the standard, even if it is a very old standard and many compilers don't care...

No problem. If we end up merging Meson and the Github Actions added there, it will show these problems in the future. Which should hopefully lead to no changes being merged which have these problems.

**Review by matsbn — APPROVED** [review]
Great to fix these deviations from the standard that some compilers complain about.

**Pull request merged**
