### PR TITLE
fix sedfluxb for release-1.6 branch

### PR DESCRIPTION
**Pull request by TomasTorsvik**
Same as PR #401 , but for release-1.6

### CODE REVIEW

**Review by jmaerz — APPROVED** [review]
Hi @TomasTorsvik , thanks for providing this fix in the release branch. Any chance to cherry pick this bug fix on top of former release branches (i.e. BLOM version for NorESM2.1(?) that enables MCT-based, to large extend CMIP6-backward-compatible BLOM runs)?

**Comment by TomasTorsvik** [comment]
> Hi @TomasTorsvik , thanks for providing this fix in the release branch. Any chance to cherry pick this bug fix on top of former release branches (i.e. BLOM version for NorESM2.1(?) that enables MCT-based, to large extend CMIP6-backward-compatible BLOM runs)?

@jmaerz - I'm happy to have this fix also for NorESM2.1, I didn't check if it was relevant for `release-1.5`. I guess we don't do bug fixes for NorESM2.0 (unless it was introduced there at some stage after v2.0.1). 

In this case I found it easier to just re-apply the code change. With cherry-pick I'm always a bit nervous about pulling in changes that were not intended, but in principle I don't have anything against it.

**Comment by jmaerz** [comment]
I fear, it was introduced with the N-cycle #269 ( 916352e) - hence any release afterward (+ NorESM pointing to those releases)... I am really sorry for this hassle.

**Comment by TomasTorsvik** [comment]
@jmaerz - No worries. I gather this doesn't affect `release-1.5` in that case?

**Comment by jmaerz** [comment]
Hi @TomasTorsvik , trying to browse through the release history, yes, it would affect 1.6.0 onward. As far as I understand, changing the BLOM `user_nl` should enable running the model in a mode that is to large extend backwards compatible (apart from small bug fixes like the sediment sinking, sediment alkalinity, etc.) - trying to figure this out through #354 which means that the current fix should suffice then. Thanks again!

**Pull request merged**
