### PR TITLE
Breaking CMIP6 backward compatibility through bugfixes - iHAMOCC ready for NorESM2.1

### PR DESCRIPTION
**Pull request by jmaerz**
**This PR breaks CMIP6 backward compatibility since it introduces a few bugfixes to `master`:**
- sediment alkalinity
- sinking of free dust with potential effects on burial rates 
- burial time smoothing (time smoothing was formerly applied multiple times)
- OMP fixes (1D setup with iHAMOCC now reproducible also when OMP is switched on)

This PR makes `master` ready for the NorESM2.1 milestone (at least from the iHAMOCC point of view).

### CODE REVIEW

**Review by JorgSchwinger — APPROVED** [review]
Looks good, thank you.

**Review by mvertens — APPROVED** [review]
Looks good.
I have two questions: 
1) What tag will we use for this and moving forwards
2) Can we decide on regression tests that can be carried out with this tag and subsequent tags?

**Comment by jmaerz** [comment]
@mvertens, @JorgSchwinger and @TomasTorsvik : I suspect that we should briefly talk about the tagging during the BLOM core meeting tmw. Any opinion on this @JorgSchwinger? - see also discussion #295. Wrt the regression testing: I would be happy to incorporate the **automated** regression testing in my daily routine of coding (thus far mainly manually done). I hope that the full support will be available through the NorESM2.1 release. Wrt to specific testcases, I see that some combinations are probably needed - particularly in combination with the hybrid coordinates, at some point potentially with the new SI units, potentially a combination of HAMOCC logicals and potentially wrt to air-sea fluxes. 

Wrt to merging #314 and #315, I'll wait a bit longer today for Tomas, but I suspect that he's busy with the workshop so that I merge the stuff in the afternoon.

**Comment by JorgSchwinger** [comment]
I don't have any strong opinion on the tagging-question. Using `vX.Y.Z` and updating z automatically sounds ok to me. But I'm fine with whatever is decided tomorrow (I can't make it)

**Comment by jmaerz** [comment]
@JorgSchwinger , ok, thanks for the input on the tagging. I suspect it will be a decision between Mats and Mariana then.

**Comment by jmaerz** [comment]
I performed another regression testing between an earlier stage of the `feature-hamocc_beyond-CMIP6` branch and the latest stage that we will merge with this PR into `master`. It looked all good and we are all set for merging the PR, making `master` ready for the NorESM2.1.

**Pull request merged**
