### PR TITLE
Update release-1.4

### PR DESCRIPTION
**Pull request by TomasTorsvik**
Update release-1.4 branch with 3 latest commits from `master`. 

The release-1.4 branch should still be backward compatible with CMIP6 output.

### CODE REVIEW

**Comment by TomasTorsvik** [comment]
I should do some testing before submitting this PR for final review.

**Review by mvertens — APPROVED** [review]

**Comment by TomasTorsvik** [comment]
Bit-identical results obtained for NOINYOC T62_tn21 compared with reference CMIP6 run (except for diagnostic fields reported in changelog for release-1.3).

Please give feedback if further testing is needed (or you find something strange when running your own test).

If approved, I will tag this branch and prepare a changelog for `release-1.4`.

**Comment by TomasTorsvik** [comment]
@JorgSchwinger , @jmaerz , @mvertens , @matsbn 
After discussing with Mats today, I would like to push this to `release-1.4` today, and prepare for a new release branch to be used for the upcoming `noresm2.1`. After pushing this PR, I will prepare a tag and changelog. The branch for `noresm2.1` should go from an updated `master`.

**Comment by JorgSchwinger** [comment]
Hi, there is a couple of things that have updated master after this, which should be included. Also, there is still the discussion whether we can include the ifdef-changes. If the latter is possible, I would really think it would be good to have this in the last CMIP6 backwards compatible release.

**Comment by mvertens** [comment]
I will have PR hopefully by Monday with #ifdef changes that don't have the flux modifications.

**Comment by TomasTorsvik** [comment]
@JorgSchwinger , @mvertens ,
thanks for responding. I will wait with pushing to `release-1.4`. Once we have included the #ifdef changes, we can see if it makes most sense to move the `release-1.4` branch or update it by cherry picks from `master`.

**Comment by mvertens** [comment]
@TomasTorsvik - I am not running MCT tests right now with my regression testing - but I am fine doing that for this PR.
What MCT test(s) should I run both with master and my PR and in what checkout? 
One option is to checkout release2.0.6 - and update BLOM to release1.4 and then run the test you suggest - and then update BLOM to my PR and run the same test and show that they are bfb. Could you clarify what I should do?

**Comment by TomasTorsvik** [comment]
@mvertens - I was testing `noresm2.0.6` with BLOM version from the `release-1.4` branch. As far as I could tell, this is still BFB compatible with CMIP6 (noresm2.0.5), except for some diagnostic fields that changed in `release-1.3`.
Just now I was running a test on NOINYOC_T62_tn21 with `noresm2.0.6` and BLOM `master` branch. This was also BFB with noresm2.0.5.
I think a similar test, SMS but not necessarily NOINYOC_T62_tn21, maybe even with and without this PR, would be sufficient.

**Comment by JorgSchwinger** [comment]
I think a fully coupled test (any compset, piControl, HIST, 1pctco2...) in addition to NOINYOC would be nice. Just to be sure.

**Comment by mvertens** [comment]
@JorgSchwinger @TomasTorsvik - I just ran two tests - NOINYOC_T62_tn14 using noresm2.0.6 - with BLOM master and my branch. The results were bfb after a 5 day run.  If one of you two could suggest a fully coupled case to run for 5 days with those two code bases out of noresm2.0.6 that would be really helpful.

**Comment by JorgSchwinger** [comment]
@mvertens, I think a fully coupled historical could be a good test, if you agree (compset NHISTfrc2, resolution f19_tn14). You would need restart files for this, which are under /nird/projects/NS9560K/noresm/cases/N1850_f19_tn14_11062019/rest/1600-01-01-00000/

**Comment by mvertens** [comment]
@JorgSchwinger - On Friday I ran two fully coupled tests using noresm2.0.6 - SMS.f19_tn14.N1850esm.betzy_intel. The first used used BLOM master and the second tests used this PR for BLOM. The results were bfb after 5 days.
This is outined in #280. I am also happy to do the test you suggested if you feel that would be useful.

**Comment by JorgSchwinger** [comment]
Ok, I see - I was confused about the different PRs. No need to have further fully coupled tests for now.

**Comment by TomasTorsvik** [comment]
The `release-1.4` branch will be moved to reflect the latest developments in `master`, once #280 has been merged and tested. This branch will not be merged.

**Pull request closed without merging**
