### PR TITLE
Add Meson build system

### PR DESCRIPTION
**Pull request by nordmoen**
Hi BLOM team,

In an effort to make it easier to work with the BLOM source code, I have added a new build system. This PR adds the possibility of building BLOM with [Meson](https://mesonbuild.com/).

Meson was chosen because it is a modern build system
 - Works on all systems where BLOM could be expected to run
 - Supports different compilers
 - Fast and efficient
 - Handles dependencies

Unfortunately this PR is not in a perfect working state. I have not gotten `dimensions.F` to build properly, but I have tested the setup with branch `feature_GPU_channel` which works. So before this is merged we can hopefully together fix this issue so that one can start to build BLOM with Meson.

### CODE REVIEW

**Comment by matsbn** [comment]
I gave the PR a try and Meson looks very promising, thanks for contributing @nordmoen! My testing was on a Mac and I made a minor tweak to make it build on this system. Also, I made some changes to allow the build directory to be located elsewhere than in the source root. Is it OK that I add commits to this PR?

The pending PR https://github.com/NorESMhub/BLOM/pull/61 changes a number of source file names and would require changes in the various meson.build files. Although I believe there would be no conflict, we also need to make sure that the Meson build system does not interfere with building BLOM in NorESM.

It seems Meson is not installed on Betzy and Fram. Is it best to ask Sigma2 to install it for further testing, or should users install Meson personally as a Python package?

**Comment by nordmoen** [comment]
Please, by all means add commits to this PR to make it better!

One intention I had for this PR, and the reason it is still in draft mode, is that it could be merged into its own branch for now so that further testing can be done without disrupting your other work. This would also allow for changes such as #61 to be merged without having to coordinate with this PR.

I'll ensure Meson is installed on Betzy and Fram.

**Comment by nordmoen** [comment]
Meson should now be available on Betzy and Fram (if it is not visible, use `module --show_hidden avail Meson`).

One challenge that still remains, not sure how important it is for you, is that `dimensions.F` cannot be compiled with `gfortran`. Is this something we should look into?

**Comment by matsbn** [comment]
It is important that the code compiles with gfortran. I have not experienced any problems with dimensions.F and gfortran on my Mac. The version I use is "GNU Fortran (MacPorts gcc10 10.2.0_4) 10.2.0". I have experienced some some other issues using gfortran, e.g. I have to compile with option "-fallow-argument-mismatch" when enabling MPI but this should be unrelated to dimensions.F.

**Comment by nordmoen** [comment]
On Fedora 33 with `gfortran` version `10.2.1` I get

```bash
FAILED: blom.p/meson-generated_.._bld_dimensions.F.o                                                          
gfortran -Iblom.p -I. -I.. -Icesm -I../cesm -Iphy -I../phy -Itrc -I../trc -I/usr/include -I/usr/lib64/gfortran/modules 
-fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Wextra -g -fdefault-real-8 -fconvert=big-endian -DLEVITU
S2X -DTKE -DTKEADV -DIDLAGE -fopenmp -Jblom.p -o blom.p/meson-generated_.._bld_dimensions.F.o -c bld/dimensions.F      
bld/dimensions.F:36:18:                                                                                                
                                                                                                                       
   36 |       data ii_pe/                                                                                              
      |                  1                                                                                             
Error: Syntax error in DATA statement at (1)                                                                           
bld/dimensions.F:43:18:                                                                                                
                                                                                                                       
   43 |       data jj_pe/                                                                                              
      |                  1                                                                                             
Error: Syntax error in DATA statement at (1)                                                                           
```

**Comment by matsbn** [comment]
There seems to be an issue with the lines that are supposed to follow and make up the complete data statement. Can you make the generated dimensions.F available?

**Comment by nordmoen** [comment]
[Gist of default `gx1v5` grid](https://gist.github.com/nordmoen/95f7b72d2d6abc05e63c0a87f34f31c7) that generated the error above.

**Comment by matsbn** [comment]
The problem seems to be in generating the dimensions.F file, not gfortran. The data statements related to variables ii_pe and jj_pe are incorrect Fortran syntax, while the data contained in i0_pe and j0_pe seems to have correct syntax but incorrect values. Here is the file that was generated for me: [dimensions.F](https://gist.github.com/matsbn/a0eaf6ccbeba9506fb6f701d655114fe). I guess it is a bash issue with blom_dimensions, the script that generates dimensions.F.

**Comment by nordmoen** [comment]
There seems to be a discrepancy between the handling of `read -d " "` between macOS and Linux bash. Adding `if` statements ignoring empty input [solved the problem on Linux and works on macOS as well](https://github.com/nordmoen/BLOM/actions/runs/500483532).

```bash
#!/bin/bash
#
# ------------------------------------------------------------------------------
# Copyright (C) 2009-2020 Mats Bentsen
#
# This file is part of BLOM.
#
# BLOM is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# BLOM is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with BLOM. If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------
#
# The purpose of this script is to generate a BLOM module file,
# dimensions.F, containing all dimension parameters and grid
# partitioning information. The necessary information is taken from
# patch.input files for the appropriate processor count.
#
set -e

sn=`basename $0`
usage="Usage: $sn -n pes [-k kdm] [-d directory] [-s]\nPurpose: write dimensions.F containing all dimension parameters and grid\npartitioning information for BLOM.\nOptions:\n -n pes\t\tnumber of processing elements.\n -k kdm\t\tvertical dimension (default kdm=1).\n -d directory\tdirectory to search for patch.input files (default\n\t\tcurrent working directory).\n -s\t\tdo not write dimensions.F."

#
# Get options
#
kdm=1
patchdir=$PWD
nowrite=0
error=0
while getopts ":n:k:d:s" opt; do
  case $opt in
    n) npes=$OPTARG;;
    k) kdm=$OPTARG;;
    d) patchdir=$OPTARG;;
    s) nowrite=1;;
    \?) echo "$sn: Invalid option: -$OPTARG" >&2
        error=1;;
    :) echo "$sn: Option -$OPTARG requires an argument." >&2
       error=1;;
  esac
done
if [[ -z $npes || $error -eq 1 ]]; then
  echo -e "$usage" >&2
  exit 1
fi

#
# Check for availability of suitable patch.input file
#
if [ ! -d $patchdir ];  then
  echo "$sn: Directory $patchdir for patch.input files does not exist!" >&2
  exit 1
fi
if [ ! -e $patchdir/patch.input.$npes ];  then
  echo "$sn: Cannot find patch.input file for $npes processors!" >&2
  pil=($patchdir/patch.input.*)
  if [ "${pil[0]##*.}" == "*" ]; then
    echo "$sn: no patch.input files are available!" >&2
  else
    for ((i=0; i < "${#pil[@]}"; i++)); do
      pil[i]=`tail -c11 <<< "000000000${pil[i]##*.}"`
    done
    pil=(`for ((i=0; i < "${#pil[@]}"; i++)); do echo ${pil[i]}; done | sort`)
    echo "$sn: Available processor counts: ${pil[@]##*00000}" >&2
  fi
  exit 1
fi

#
# Read all lines in the patch input file
#
l=0
while read line[l]; do
  l=$((l+1))
done < $patchdir/patch.input.$npes

#
# Get various parameters
#
read npesfile npe mpe idm jdm ibig jbig nreg minsea maxsea avesea <<< ${line[1]}

#
# Check consistency of processor count in argument and patch.input file
#
if [[ npes -ne npesfile ]]; then
  echo "$sn: Inconsistent processor count in argument ($npes) and patch.input file ($npesfile)." >&2
  exit 1
fi

if [[ nowrite -eq 1 ]]; then
  exit 0
fi

#
# Get 1st dimension tile offsets and extents
#
l=3
m=0
i=0
j=0
while [ $m -lt $mpe ]; do
  n=0
  while [ $n -lt $npe ]; do
    while read -d " " i0_pe[i]; do
      if [[ ${i0_pe[i]} -eq " " ]]; then
        continue
      fi
      i0_pe[i]=$((${i0_pe[i]}-1))
      i=$((i+1))
      n=$((n+1))
    done <<< ${line[l]#*=}" "
    l=$((l+1))
  done
  n=0
  while [ $n -lt $npe ]; do
    while read -d " " ii_pe[j]; do
      if [[ ${ii_pe[j]} -eq " " ]]; then
        continue
      fi
      j=$((j+1))
      n=$((n+1))
    done <<< ${line[l]#*=}" "
    l=$((l+1))
  done
  m=$((m+1))
done

#
# Get 2st dimension tile offsets and extents
#
l=$((l+1))
m=0
while [ $m -lt $mpe ]; do
  while read -d " " j0_pe[m]; do
    if [[ ${j0_pe[m]} -eq " " ]]; then
      continue
    fi
    j0_pe[m]=$((${j0_pe[m]}-1))
    m=$((m+1))
  done <<< ${line[l]#*=}" "
  l=$((l+1))
done
m=0
while [ $m -lt $mpe ]; do
  while read -d " " jj_pe[m]; do
    if [[ ${jj_pe[m]} -eq " " ]]; then
      continue
    fi
    m=$((m+1))
  done <<< ${line[l]#*=}" "
  l=$((l+1))
done

#
# Create dimensions.F
#
cat <<EOF >dimensions.F
      module dimensions
c
c --- itdm  = total grid dimension in i direction
c --- jtdm  = total grid dimension in j direction
c --- kdm   =       grid dimension in k direction
      integer    itdm,jtdm,kdm
      parameter (itdm=$idm,jtdm=$jdm,kdm=$kdm)
c
c --- ijqr  = total number of active tiles
c --- iqr   = maximum number of tiles in i direction
c --- jqr   = maximum number of tiles in j direction
c --- idm   = maximum single tile grid dimension in i direction
c --- jdm   = maximum single tile grid dimension in j direction
      integer    ijqr,iqr,jqr,idm,jdm
      parameter (ijqr=$npes,iqr=$npe,jqr=$mpe,idm=$ibig,jdm=$jbig)
c
c --- region type (nreg=-1: unknown,
c ---              nreg= 0:   closed/closed,
c ---              nreg= 1: periodic/closed,
c ---              nreg= 2: periodic/arctic,
c ---              nreg= 3: periodic/periodic
c ---              nreg= 4:   closed/periodic)
      integer    nreg
      data nreg/$nreg/
c
c --- i0_pe = 1st dimension tile offsets
c --- ii_pe = 1st dimension tile extents
c --- j0_pe = 2nd dimension tile offsets
c --- jj_pe = 2nd dimension tile extents
      integer, dimension(iqr,jqr) :: i0_pe,ii_pe,j0_pe,jj_pe
EOF

echo -n "      data i0_pe/" >> dimensions.F
P=72
i=0
while [ $i -lt $((npe*mpe)) ]; do
  if [ $((P+${#i0_pe[i]}+1)) -gt 72 ]; then
    echo -ne "\n     .  " >> dimensions.F
    P=8
  fi
  echo -n "${i0_pe[i]}" >> dimensions.F
  if [ $i -lt $((npe*mpe-1)) ]; then
    echo -n "," >> dimensions.F
  else
    echo "/" >> dimensions.F
  fi
  P=$((P+${#i0_pe[i]}+1))
  i=$((i+1))
done

echo -n "      data ii_pe/" >> dimensions.F
P=72
i=0
while [ $i -lt $((npe*mpe)) ]; do
  if [ $((P+${#ii_pe[i]}+1)) -gt 72 ]; then
    echo -ne "\n     .  " >> dimensions.F
    P=8
  fi
  echo -n "${ii_pe[i]}" >> dimensions.F
  if [ $i -lt $((npe*mpe-1)) ]; then
    echo -n "," >> dimensions.F
  else
    echo "/" >> dimensions.F
  fi
  P=$((P+${#ii_pe[i]}+1))
  i=$((i+1))
done

echo -n "      data j0_pe/" >> dimensions.F
P=72
i=0
while [ $i -lt $((npe*mpe)) ]; do
  n=$((i/npe))
  if [ $((P+${#j0_pe[n]}+1)) -gt 72 ]; then
    echo -ne "\n     .  " >> dimensions.F
    P=8
  fi
  echo -n "${j0_pe[n]}" >> dimensions.F
  if [ $i -lt $((npe*mpe-1)) ]; then
    echo -n "," >> dimensions.F
  else
    echo "/" >> dimensions.F
  fi
  P=$((P+${#j0_pe[n]}+1))
  i=$((i+1))
done

echo -n "      data jj_pe/" >> dimensions.F
P=72
i=0
while [ $i -lt $((npe*mpe)) ]; do
  n=$((i/npe))
  if [ $((P+${#jj_pe[n]}+1)) -gt 72 ]; then
    echo -ne "\n     .  " >> dimensions.F
    P=8
  fi
  echo -n "${jj_pe[n]}" >> dimensions.F
  if [ $i -lt $((npe*mpe-1)) ]; then
    echo -n "," >> dimensions.F
  else
    echo "/" >> dimensions.F
  fi
  P=$((P+${#jj_pe[n]}+1))
  i=$((i+1))
done

cat <<EOF >>dimensions.F
c
      end module dimensions
EOF

exit 0
```

**Comment by matsbn** [comment]
Great you found a solution to bash issue, @nordmoen. In my experience, it has been working on all the Linux versions of various Sigma2 machines the last decade or so, but apparently bash has some inconsistency in its behaviour. Probably good to consider something more robust eventually to replace this ancient script.

**Comment by nordmoen** [comment]
I tried to merge this PR with current Master, I see that Github is slightly confused, but it should be correct.

**Comment by nordmoen** [comment]
To have a branch I created a new `meson` branch which the changes in this branch were added to.

**Pull request closed without merging**
