### PR TITLE
Hello World example with CUDA Fortran

### PR DESCRIPTION
**Pull request by setmar**
The actual execution of the CUDA Fortran kernel needs to be enabled in drivers/nocoupler/blom.F

### CODE REVIEW

**Comment by TomasTorsvik** [comment]
Hi @setmar @YanchunHe ,
I see there are conflicts in the build/pgi.make and build/puhti.job files. These should be resolved before merging the changes. It doesn't seem to be anything major. @setmar , if you agree with the suggested fixes, could you include these in your pull request (update "feature_GPU_channel2" in your fork)?

pgi.make: The flag "-Mrecursive" has been removed in the current repo (the line including this flag is commented out by Yanchun). This allows local variables on the stack. 
__Suggested fix:__ Remove the "-Mrecursive" flag in the pull request.

puhti.job: the diff is between pull request and current repo is

```
<<<<<<< feature_GPU_channel2
 
# profiling
#LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/netCDF/lib srun nvprof --cpu-profiling on ./blom
 
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/netCDF/lib srun ./blom
=======
if [ ! -d run ] ; then
mkdir run
fi
cp ./blom run/
cp /scratch/project_2003520/data/* run/
cd run
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/scratch/project_2003520/netCDF/lib/
srun ./blom
>>>>>>> feature_GPU_channel2

```
__Suggested fix:__ Update pull request according to current repo

**Comment by YanchunHe** [comment]
For `puhti.job`, if the NetCDF library is explicitly included in the `pgi.make` file, it is not necessary to include it to the `LD_LIBRARY_PATH' environment variable, right?

**Comment by monsieuralok** [comment]
> 
> 
> For `puhti.job`, if the NetCDF library is explicitly included in the `pgi.make` file, it is not necessary to include it to the `LD_LIBRARY_PATH' environment variable, right?

Yes, we should have LD_LIBRARY_PATH as we are doing for NorESM by loading module at runtime.

**Comment by setmar** [comment]
Thanks for the feedback. The issues should be resolved now.

**Comment by TomasTorsvik** [comment]
Thanks @setmar ! 
I did a "squash and merge" to keep the main repo a bit tidy, so you might need to reset your fork/local clone to the upstream to sync the commit history.

**Pull request merged**
