### PR TITLE
Add error message if user_nl_blom includes hash comments

### PR DESCRIPTION
**Pull request by TomasTorsvik**
Same as https://github.com/NorESMhub/BLOM/pull/448, applied for the `master` branch.

### CODE REVIEW

**Review by jmaerz — APPROVED** [review]
Hi @TomasTorsvik , technically approved, but I just realize that one could have potentially handled it also as a comment similar to the lines above (l. 1338) by
```
line=remove_user_nl_comment(line)
```
- not sure, though, whether this would induce other side effects... - similarly for the other cases...

**Comment by TomasTorsvik** [comment]
> Hi @TomasTorsvik , technically approved, but I just realize that one could have potentially handled it also as a comment similar to the lines above (l. 1338) by
> 
> ```
> line=remove_user_nl_comment(line)
> ```
> 
>     * not sure, though, whether this would induce other side effects... - similarly for the other cases...

@jmaerz - True, but the old `user_nl_blom` files use a different format for setting variables, using a `set` keyword. One could also search for `set`, but this could cause issues if a variable name happened to start with `set...`. If the `user_nl_blom` file use # comments, probably something else could be wrong as well.

**Comment by jmaerz** [comment]
Hi Tomas, thanks for clarification. I guess, moving forward in this case is totally fine - from my side, just go ahead with the PR.

**Comment by JorgSchwinger** [comment]
It's fine for me including this, but I think it is actually not necesarry. 

The starting point was that older user_nl_blom files were not compatible with noresm 2.0.9. This was an issue because this model version is still (compatible to) our CMIP6 model, so a user could expect also the old user namelist files to work here.

However moving forward, there is no reason to expect this - format of user_nl_blom has changed (there are also other changes, not only the # vs !...), but that is fine because it is a new model version.

**Review by JorgSchwinger — APPROVED** [review]

**Comment by TomasTorsvik** [comment]
> It's fine for me including this, but I think it is actually not necesarry.
> 
> The starting point was that older user_nl_blom files were not compatible with noresm 2.0.9. This was an issue because this model version is still (compatible to) our CMIP6 model, so a user could expect also the old user namelist files to work here.
> 
> However moving forward, there is no reason to expect this - format of user_nl_blom has changed (there are also other changes, not only the # vs !...), but that is fine because it is a new model version.

Yes, hopefully this will not have much use, at least when going to NorESM2.5. At the moment this change will make it into the planned `release-1.7` as well.

**Pull request merged**
