### PR TITLE
Major iHAMOCC code update: simplification of BLOM-iHAMOCC interface including initialization, changed handling of boundary conditions

### PR DESCRIPTION
**Pull request by JorgSchwinger**
Tests: I found that the new code produces bit-for-bit identical results both in OMIP simulations, and in emission driven fully coupled cases.

### CODE REVIEW

**Review by mvhulten — APPROVED** [review]
That's a big diff!

**Review by TomasTorsvik — COMMENTED** [review]
This pull request introduces a lot of changes at once. It is difficult to get a general overview over what has changed, so I tried to make a summary for myself. Most changes seem to be restructuring of existing parts, but with less copying of fields when going from BLOM to HAMOCC. Is there anything important that I miss in this summary?

Summary of changes in this pull request:
- commit 1: Include new module 'mo_vgrid.f90' for vertical grid definition and handling. This module takes over variables from 'mo_param1_bgc' and 'mo_biomod', and replaces subroutines 'calc_bot' and 'calc_idepth'.
- commit 2: Minor fix
- commit 3: Major changes to HAMOCC initialization
  + 'hamocc_init.F' extended to replace 'ini_hamocc.F90', 'inibgc.F' and 'restart_hamoccrd.F'
  + New module 'mo_intfcblom.F90' replaces header files 'common_bgc.h' and 'common_bgcs.h'
  + Split the original BELEG_BGC in two parts, BELEG_PARM and BELEG_VARS
- commit 4: Changes to boundary conditions
  + 'mo_fedep.F90' replaces 'get_dust.F90'
- commit 5: merge with upstream/master
- commit 6: merge branch (to master?)

I'm wondering how the history will change considering the merging in the last two commits in this pull request. Is it possible to do a 'dry run' of the pull request merging to look at this before doing the full merging?

**Comment by TomasTorsvik** [comment]
Never mind about the 'dry run'. I looked at the Insights/Network and see that the 'master' you merged into is in sync with upstream, except for 'commit 6'. It should be OK to do a merging of this pull request.

**Comment by JorgSchwinger** [comment]
Yes, this was a lot of changes. Sorry for that, but these could only be done in one go. Your summary above is fine. Sorry about the confusion with the last two commits - this is due to myself not being so familiar with github. I should have (and planned to) kept this in my local branch and make a pull request from there. But then there came in another pull request that modified some of the files I was dealing with - so I though it would be better to merge everything into my master - now I see that this wasn't the smartest solution. But other than it is not nice and a bit confusing it will do the right thing.

**Review by TomasTorsvik — APPROVED** [review]

**Pull request merged**
