### PR TITLE
Remaining copyright notices, LGPL license and some code cleanup

### LINKED ISSUE #2: License for BLOM
It would be useful to clarify the license for BLOM. Assuming we are free to chose whatever license, I would suggest (having consulted with Marco) to go for either a GNU Lesser General Public License v3.0 (lgpl-3.0) or an Apache license 2.0 (apache-2.0).

### PR DESCRIPTION
**Pull request by matsbn**
Inserted copyright/license notice in remaining files. Removed dynamic sea-ice code and some obsolete files. Added GPL and LGPL license files and updated README.md with license information.

### CODE REVIEW

**Review by TomasTorsvik — APPROVED** [review]
This looks fine to me. I noticed you use the f90 comment style throughout ('!' instead of 'c'), but this should still work for fixed-form files when inserted in the first column. Otherwise I don't have any specific comments.

**Comment by TomasTorsvik** [comment]
@matsbn 
I think it would be a good idea if you suggest reviewers and assignees for this pull request. If the pull request is connected to an open issue, I suggest the people who have commented on the issue could be invited to review the changes. Perhaps this is not practical if a lot of people have been involved in a discussion, but I don't think it can do any harm to invite people to review. 

I linked the license issue to this pull request, so the issue should be closed once the pull request is merged.

The assignees are the ones who should sign off on the pull request. At the moment I have an option to merge the pull request, and I guess all blom-core members have this option, but I'm not going to "pull the trigger" on anything that I'm not assigned to. You can probably assign it to anyone you like, including yourself, but I think it is more tidy if it is made clear who will have the last word on the merging.

**Comment by matsbn** [comment]
Good idea to suggest reviewers. Pull requests is still new to me so I need to improve on proper handling of things like this. I chose f90 comment style since the plan is anyway to modernise the f77 style code. I have checked that it compiles fine with gcc and intel compilers.

**Review by JorgSchwinger — APPROVED** [review]

**Review by mvhulten — APPROVED** [review]
Looks very good to me.

**Pull request merged**
