### PR TITLE
Fix the compset name for the SSP5-3.4 scenario to conform to the name…

### PR DESCRIPTION
**Pull request by JorgSchwinger**
… already used in other NorESM2 components

### CODE REVIEW

**Comment by JorgSchwinger** [comment]
This is necessary since in CLM the name SSP534 (without "OS") is already in use. To make this work also the other components need to be updated.

**Comment by JorgSchwinger** [comment]
Probably good to cherry-pick this into the release branch?

**Review by TomasTorsvik — APPROVED** [review]
Is this a change that needs to be implemented across several NorESM components? If so, it would make sense to raise this as an issue in the NorESM repository, and coordinate for a new bug-fix release.

**Comment by JorgSchwinger** [comment]
Well, it is generally not a bug fix. The SSP5-3.4 scenario was run by Ali and has been published to ESGF, but the compset definition has not been included into a NorESM2 release yet.

So yes, I have more changes for the other components, but I'm not sure which branch etc. they should go into.

**Comment by matsbn** [comment]
Agree that this could be cherry-picked into release branches and then create v.1.1.1 and/or v1.2.1 release tags. Maybe the update to release branches should wait until compset changes for other components are in place to prepare for a coordinated NorESM bug fix release (although not really a bug).

**Review by matsbn — APPROVED** [review]
Seems fine to merge into master.

**Pull request merged**
