### PR TITLE
Allocatable tracer array

### LINKED ISSUE #105: Enable tracer count to be determined at run time
For discussion:
If we should have a BLOM/iHAMOCC model that can accommodate different BGC tracer counts at run time, it is necessary to first make some changes in the BLOM/iHAMOCC interface, and the way that the tracer module works. I propose the following changes:

- make "ntr" adjustable at runtime through a new subroutine ("set_trc") and change the attribute from PARAMETER to PROTECTED.
- Make the tracer arrays allocatable: trc, trcold, uflxtr, vflxtr, trflx
- Make a new "allocate_tracers" subroutine
- Set value of "ntrbgc" based on variable settings in input namelist (e.g. "with_cfc", "with_natDIC", "with_AGG", "with_ciso" as .true. or .false.)
  - advantage: No need for "double booking" of i_base, i_iso, i_cfc, i_agg, i_nat_dic 

This setup will require the following procedure:
1. Read namelist for iHAMOCC tracer variables
2. Set "ntrbgc"
3. Set "ntr"
4. Allocate tracer arrays

After that the model structure should be the same as before, so I don't think there is a need for major restructuring of the code. However, the tracer allocation will have to be included somewhere in the initialization procedure.

### PR DESCRIPTION
**Pull request by TomasTorsvik**
This is a suggestion for changing the tracer array from static to allocatable. I have also moved some things around in the module, but this doesn't make any difference for the final outcome.

### CODE REVIEW

**Comment by TomasTorsvik** [comment]
From https://github.com/NorESMhub/BLOM/issues/105#issuecomment-919024257 :

Here are results from some tests I did on Betzy and Fram:
[alloc_array_perf.txt](https://github.com/NorESMhub/BLOM/files/7161071/alloc_array_perf.txt)

It seems that there still can be some issues when replacing static arrays with allocatable ones, but perhaps only for specific compiler settings or case parameters. For most tests the differences were fairly small.

**Comment by JorgSchwinger** [comment]
I don't know why, but github won't let me add an review. 

So I just coment here: looks good to me, I would be fine with including this.

**Review by JorgSchwinger — APPROVED** [review]
ok, now it works...

**Comment by TomasTorsvik** [comment]
It turns out that the code runs with ``call xcbcst(ntr)`` even if ``ntr`` is declared ``protected``, so I removed the ``num_tracers`` variable. I also ran the fuk95 case without problems from the branch.

**Pull request merged**
