### PR TITLE
Minor fixes for configuration and namelist creation

### PR DESCRIPTION
**Pull request by JorgSchwinger**

### CODE REVIEW

**Review by mvertens — APPROVED** [review]
Thanks for this.

**Review by TomasTorsvik — APPROVED** [review]
Thanks, looks good to me :+1: 
Some CI-tests timed out. Will see if I can re-run, but shouldn't be essential.

**Comment by jmaerz** [comment]
Hi @JorgSchwinger , it shouldn't conflict with #305, but maybe it would be good to merge it nevertheless (I took myself out as a reviewer).

**Comment by JorgSchwinger** [comment]
I have put this on hold since it will interfere with the regression testing. There will be a fix needed since the C-isotope code cannot be switched on via user-namelist, but needs to go via env_run.xml.

@mvertens if you can tell me how to fix this, I could include it into this PR. Unless you think it is easier if you fix this after merging this PR?

**Comment by mvertens** [comment]
@JorgSchwinger - 

 in blom/cime_config/testdefs/testmods_dirs/blom/hamocc1/ 
    add a file shell_commands and in that file add the line
./xmlchange HAMOCC_CISO=TRUE
    and in user_nl_blom remove the line
 use_cisonew = .true.

You need to do this for every new xml variable that was introduced for the user_nl_blom variables that are in the user_nl_blom file

You should also do this for in blom/cime_config/testdefs/testmods_dirs/blom/hamocc2/

That should be it. Does that make sense?

**Comment by JorgSchwinger** [comment]
Ok thank you for the instructions @mvertens, done. 

I guess then this PR can be merged?

**Comment by mvertens** [comment]
That would be fine with me.

**Pull request merged**
