### PR TITLE
Making MKS units default

### LINKED ISSUE #338: Transition from "cgs" to "mks" as default for NorESM2.3?
@matsbn , @jmaerz , @JorgSchwinger , @milicak 
As far as I know, we now have equivalent output for the "mks" and "cgs" units. Would it make sense to transition to "mks" as default for the upcoming NorESM2.3 release?

TODO:
- [x] Run coupled tests with interactive DMS to verify climatological similarity
- [x] Modify restart system: continue runs using MKS that have been started with CGS

### PR DESCRIPTION
**Pull request by matsbn**
MKS units are now default in standalone mode and when coupled to NorESM. The restart procedure has been modified to allow continuing from a restart with a different unit system (MKS/CGS) than currently configured. Bugs related to MKS units in the NUOPC interface and diagnosed momentum flux has been corrected.

Tested with NOIIAJRAOC20TR compset. With CGS units, no change in results and correct restart. With MKS units, no change in results (except diagnosed momentum flux) and correct restart. Continuing with MKS units from a restart in CGS units gives similar deviations in results as expected from the unit change. Not tested with NUOPC coupler.

@mvertens, the modified restart procedure led to a substantial refactoring of the restart routines. Hopefully, this will not cause too many problems progressing with PR https://github.com/NorESMhub/BLOM/pull/317.

### CODE REVIEW

**Review by JorgSchwinger — APPROVED** [review]
Looks good to me. Very usefule to have the restart capabilities!

**Comment by mvertens** [comment]
@matsbn - thanks for pointing this out. I've been updating #317 as master is updated.

**Review by mvertens — APPROVED** [review]

**Comment by mvertens** [comment]
@matsbn - that said - it would be good to know when #317 can be brought in and plan for that. I do feel it will modernize the code and make it more robust.

**Review by TomasTorsvik — APPROVED** [review]
@matsbn - thanks for the PR, it's great to get this in for the NorESM2.3 release.

**Review by milicak — COMMENTED** [review]
It looks good to me.

**Pull request merged**
