### PR TITLE
group call to apply_fedep together with other routines for external inputs

### PR DESCRIPTION
**Pull request by JorgSchwinger**
This PR provides a minor improvement of HAMOCC's code logic by grouping together all calls to routines that provide external inputs (dust, N-deposition, riverine input). Results are not bit-for-bit, but the differences are very small (tested with a 200 year NOINYOC_T62_tn21 run).

If there are preferences to wait with this PR until after #269 is merged please indicate this here.

### CODE REVIEW

**Review by TomasTorsvik — APPROVED** [review]
@JorgSchwinger - looks fine to me, but I suggest to put it on hold until #269 is merged as we are already in the testing phase for #269.

**Review by jmaerz — APPROVED** [review]
Thanks for taking care of this. Approved. It might be even mergable without conflicts even after #269 .

**Comment by TomasTorsvik** [comment]
@JorgSchwinger , @jmaerz - I see there is a conflict in `mo_hamocc4bcm` with this PR. Unless it's important to keep the history of this PR, it may be easier to just create a new branch from current `master` and re-apply the changes to `mo_hamocc4bcm` (rather than to merge `master` into the `fix-move_dust` branch, resolve the merge conflict there, and then merge `fix-move_dust` with `master`).

**Comment by JorgSchwinger** [comment]
@TomasTorsvik it was only a very small change, so easy to fix. I will merge this PR now.

**Pull request merged**
