### PR TITLE
Modified setting of vertical coordinate and vertical dimension

### PR DESCRIPTION
**Pull request by matsbn**
This is just a draft PR for making hybrid vertical coordinate selectable as compset option and defining vertical dimension in env_build.xml.

### CODE REVIEW

**Review by TomasTorsvik — APPROVED** [review]
Looks fine to me. I see this PR changes loading of M4AGO, so I suggest @jmaerz should have a look at it before merging.

**Comment by matsbn** [comment]
> Looks fine to me. I see this PR changes loading of M4AGO, so I suggest @jmaerz should have a look at it before merging.

Current master fails to build in NorESM2.0.* if iHAMOCC is not requested. The buildlib_2.1 was made consistent with what is already done in buildlib_2.2 (https://github.com/NorESMhub/BLOM/commit/2a0d54486525fb522df84a613fb77df0878f570d). That is, iHAMOCC and M4AGO should only be built if ocean biogeochemistry is requested. Could be made as a separate bugfix PR, but I just discovered it when testing this new functionality.

**Review by JorgSchwinger — APPROVED** [review]

**Review by jmaerz — APPROVED** [review]
Hi @matsbn , thanks for catching this (and sorry for introducing it wrongly at first place). As far as I understand, the updated file solves the compilation issue with both, ecosys on or off. Hence, I am happy to approve the PR.

**Comment by matsbn** [comment]
The PR has been updated with support for "plevel" vertical coordinate. Furthermore, hybrid vertical coordinate is now default in OMIP compsets when using NorESM2.5.

**Pull request merged**
